bookNowApp/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  get '/welcome', to: "static_pages#welcome", as: "welcome"
  get '/about', to: "static_pages#about", as: "about"
  get '/contact', to: "static_pages#contact", as: "contact"

  get '/stripe', to: "stripe#index", as: 'stripe'
  get '/stripe/authorize', to: "stripe#authorize"
  get '/stripe/oauth/callback', to: "stripe#oauth_callback"
  
  get '/webhooks', to: "hooks#redirect"
  post '/webhooks', to: "hooks#receiver"
  post '/ajax', to: "ajax#receiver", as: "ajax"

  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  get '/home', to: "sessions#index", as: 'home'
  delete '/logout', to: "sessions#logout", as: "logout"

  get 'overview' => 'overview#index'
  get 'finances' => 'finances#index'
  get 'settings' => 'settings#index'
  get 'users' => 'users#index'

  resources :users do
    resources :events, shallow: true
    resources :couples, shallow: true
    resources :assistants, shallow: true
    resources :packages, shallow: true do
      resources :items, shallow:true, only: :create
    end
  end

  get 'assistants/:id/crop', to: 'assistants#crop_avatar', as: "assistants_crop_avatar"

  # get 'users/auth/:provider/callback', to: "billing#callback"
  resources :charges

  # Catch All - 404
  get '*a', to: 'errors#routing'
end

bookNowApp/app/models/assistant.rb
class Assistant < ActiveRecord::Base
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
	validate :image_size_validation

	# build functionality - dependent destroy uploaded avatar
 
	private
  
  def image_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end
  
end

bookNowApp/app/models/couple.rb
class Couple < ActiveRecord::Base
	belongs_to :user
	has_many :events, dependent: :destroy
end

bookNowApp/app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	belongs_to :couple
end

bookNowApp/app/models/item.rb
class Item < ActiveRecord::Base
	validates_uniqueness_of :name
	has_many :package_items, dependent: :destroy
	has_many :packages, through: :package_items
end

bookNowApp/app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :user
  has_many :package_items, dependent: :destroy
  has_many :items, through: :package_items
end

bookNowApp/app/models/package_item.rb
class PackageItem < ActiveRecord::Base
  belongs_to :package
  belongs_to :item
end

bookNowApp/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :events
	has_many :couples
	has_many :assistants
	has_many :packages

  validates :email, uniqueness: {case_sensitive: false}, presence: true
  # validates :avatar_url, presence: true
end

bookNowApp/app/helpers/billing_helper.rb
module BillingHelper
end

bookNowApp/app/helpers/couples_helper.rb
module CouplesHelper
end

bookNowApp/app/helpers/errors_helper.rb
module ErrorsHelper
end

bookNowApp/app/helpers/events_helper.rb
module EventsHelper
end

bookNowApp/app/helpers/finances_helper.rb
module FinancesHelper
end

bookNowApp/app/helpers/hooks_helper.rb
module HooksHelper
end

bookNowApp/app/helpers/items_helper.rb
module ItemsHelper
end

bookNowApp/app/helpers/overview_helper.rb
module OverviewHelper
end

bookNowApp/app/helpers/packages_helper.rb
module PackagesHelper
end

bookNowApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

bookNowApp/app/helpers/settings_helper.rb
module SettingsHelper
end

bookNowApp/app/helpers/stripe_helper.rb
module StripeHelper
end

bookNowApp/app/helpers/users_helper.rb
module UsersHelper
end

bookNowApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <title>Materra | <%= yield(:title) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">

    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      body {
        width: 1px;
        min-width: 100%;
        *width: 100%;
      }
    </style>
  </head>


<body>

<div class="with-iconav">
  <% if current_user %>
  <nav class="iconav">
    <a class="iconav-brand" href="index.html">
      <%= image_tag("materra-logo-new.svg", width: "35") %>
    </a>
    <div class="iconav-slider">
      <ul class="nav nav-pills iconav-nav hi-icon-effect-9 hi-icon-effect-9b">
        <li class="<%= 'active' if params[:controller] == 'overview' %>">
          <a href="<%= overview_path %>" title="Overview" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-home hi-icon"></span>
            <small class="iconav-nav-label">Overview</small>
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'events' %>">
          <a href="<%= user_events_path(current_user) %>" title="Calendar" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-calendar hi-icon"></span>
            <small class="iconav-nav-label">Calendar</small>
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'couples' %>">
          <a href="<%= user_couples_path(current_user) %>" title="Couples" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-heart hi-icon"></span>
            <small class="iconav-nav-label">Couples</small>
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'assistants' %>">
          <a href="<%= user_assistants_path(current_user) %>" title="Assistants" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-man hi-icon"></span>
            <small class="iconav-nav-label">Assistants</small>
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'finances' %>">
          <a href="<%= finances_path %>" title="Finances" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-credit hi-icon"></span>
            <small class="iconav-nav-label">Finances</small>
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'packages' %>">
          <a href="<%= user_packages_path(current_user) %>" title="Packages" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-documents hi-icon"></span>
            <small class="iconav-nav-label">Packages</small>
          </a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'settings' %>">
          <a href="<%= settings_path %>" title="Settings" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-cog hi-icon"></span>
            <small class="iconav-nav-label">Settings</small>
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <% end %>

  <div class="container">

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
      <% if current_user %>
        <a class="navbar-brand" href="#"><%= current_user.company_name %></a>
      <% end %>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Hello, #{current_user.first_name} #{current_user.last_name}", user_path(current_user)%></li>
            <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <% flash.each do |key, value| %>
    <% if key == "notice" %>
      <%= content_tag :div, value, class: "text-center alert alert-warning" %>
    <% elsif key == "alert" %>
      <%= content_tag :div, value, class: "text-center alert alert-danger" %>
    <% else %>
      <%= content_tag :div, value, class: "text-center alert alert-success" %>
    <% end %>
  <% end %>

	<%= yield %>
	
	</div>
</div>


<!--<script src="assets/javascripts/jquery.min.js"></script>
    <script src="assets/javascripts/chart.js"></script>
    <script src="assets/javascripts/tablesorter.min.js"></script>
    <script src="assets/javascripts/toolkit.js"></script>
    <script src="assets/javascripts/app.js"></script>
    <script src="assets/javascripts/umd/tab.js"></script> -->
    <!-- 
        You need to include this script tag on any page that has a Google Map.

        The following script tag will work when opening this example locally on your computer.
        But if you use this on a localhost server or a live website you will need to include an API key. 
        Sign up for one here (it's free for small usage): 
            https://developers.google.com/maps/documentation/javascript/tutorial#api_key

        After you sign up, use the following script tag with YOUR_GOOGLE_API_KEY replaced with your actual key.
            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_GOOGLE_API_KEY&sensor=false"></script>
    -->
   <!--  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script> -->
    <!-- <script src="assets/javascripts/script.js"></script> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <script>
      // execute/clear BS loaders for docs
      $(function(){while(window.BS&&window.BS.loader&&window.BS.loader.length){(window.BS.loader.pop())()}})
    </script>
  </body>
</html>

bookNowApp/app/views/reset/password_reset.html.slim
h1 Reset#password_reset
p = @greeting + ", find me in app/views/reset/password_reset.html.slim"

bookNowApp/app/views/reset/password_reset.text.slim
' Reset#password_reset
= "\r\n" * 2
' #{@greeting + ", find me in app/views/reset/password_reset.text.slim"}

bookNowApp/app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(instance.errors.count, "error") %> prohibited this <%= instance.class %> from being saved:</h2>
    <ul>
      <% instance.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>