bookNowApp/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  get '/welcome', to: "static_pages#welcome", as: "welcome"
  get '/about', to: "static_pages#about", as: "about"
  get '/contact', to: "static_pages#contact", as: "contact"

  get '/stripe', to: "stripe#index", as: 'stripe'
  get '/stripe/authorize', to: "stripe#authorize"
  get '/stripe/oauth/callback', to: "stripe#oauth_callback"
  
  get '/webhooks', to: "hooks#redirect"
  post '/webhooks', to: "hooks#receiver"
  post '/ajax', to: "ajax#receiver", as: "ajax"

  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  get '/home', to: "sessions#index", as: 'home'
  delete '/logout', to: "sessions#logout", as: "logout"

  get 'overview' => 'overview#index'
  get 'finances' => 'finances#index'
  get 'settings' => 'settings#index'
  get 'users' => 'users#index'

  resources :users do
    resources :events, shallow: true
    resources :couples, shallow: true
    resources :assistants, shallow: true
    resources :packages, shallow: true do
      resources :items, shallow:true, only: :create
    end
  end

  get 'assistants/:id/crop', to: 'assistants#crop_avatar', as: "assistants_crop_avatar"

  # get 'users/auth/:provider/callback', to: "billing#callback"
  resources :charges

  # Catch All - 404
  get '*a', to: 'errors#routing'
end

bookNowApp/app/models/assistant.rb
class Assistant < ActiveRecord::Base
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
	validate :image_size_validation

	# build functionality - dependent destroy uploaded avatar
 
	private
  
  def image_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end
  
end

bookNowApp/app/models/couple.rb
class Couple < ActiveRecord::Base
	belongs_to :user
	has_many :events, dependent: :destroy
end

bookNowApp/app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	belongs_to :couple
end

bookNowApp/app/models/item.rb
class Item < ActiveRecord::Base
	validates_uniqueness_of :name
	has_many :package_items, dependent: :destroy
	has_many :packages, through: :package_items
end

bookNowApp/app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :user
  has_many :package_items, dependent: :destroy
  has_many :items, through: :package_items
end

bookNowApp/app/models/package_item.rb
class PackageItem < ActiveRecord::Base
  belongs_to :package
  belongs_to :item
end

bookNowApp/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :events
	has_many :couples
	has_many :assistants
	has_many :packages

  validates :email, uniqueness: {case_sensitive: false}, presence: true
  # validates :avatar_url, presence: true
end

bookNowApp/app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_action :set_user, only: [:index, :new, :create]
  before_action :confirm_logged_in
  before_action :ensure_correct_user_for_couple, only: [:edit, :show, :update, :destroy]
  before_filter :modified_couple_params, only: :create

  def index

  	@couples = @user.couples.order('wedding_date DESC')

    if @couples.any?
      starting_year = @couples.first.wedding_date.year #2019
      ending_year = @couples.last.wedding_date.year #2014
      num_years = starting_year - ending_year #2
      
      years_array = [[]]
      i = 0

      until i > num_years

      years_array.push []
        @couples.each do |couple|
          if couple.wedding_date.year == starting_year
            years_array[i].push couple
          end
        end

        i = i+1
        starting_year = starting_year-1
      end

      @years = years_array
    end
    
  	render :index
  end

  def new
    @couple = Couple.new
  end

  def create

    @couple = @user.couples.create modified_couple_params
    
    @event = Event.new
    @event.title = couple_params[:groom_first_name] + " and " + couple_params[:bride_first_name]
    @event.description = couple_params[:ceremony_address]
    @event.start_time = modified_couple_params[:wedding_date]
    @event.end_time = modified_couple_params[:wedding_date]
    @event.all_day = true
    @event.event_type = "Wedding"
    @event.user_id =  @couple.user.id
    @event.couple_id = @couple.id

  	if @couple.save && @event.save
  		redirect_to user_couples_path(@user), flash: {success: "#{@couple.groom_first_name} and #{@couple.bride_first_name} added!"}
  	else
  		render :new
  	end
  end

  def show
  	@couple = Couple.find(params[:id])
  	@date = @couple.wedding_date
  end

  private

  def modified_couple_params
    new_hash = couple_params
    date = couple_params[:wedding_date] + " 12:00:00"
    new_date = DateTime.strptime(date, '%m/%d/%Y %H:%M:%S')
    new_hash[:wedding_date] = new_date
    return new_hash
  end

	def couple_params
		params.require(:couple).permit(:wedding_date, :groom_first_name, :groom_last_name, :groom_phone, :groom_email, :bride_first_name, :bride_last_name, :bride_phone, :bride_email, :planner_first_name, :planner_last_name, :planner_phone, :planner_email, :groom_location_gr, :bride_location_gr, :ceremony_address, :reception_address, :marital_address)
	end

  def set_user
    @user = User.find params[:user_id]
  end

  def ensure_correct_user_for_couple
    ## FIX THIS LOGIC
    couple = Couple.find params[:id]
    unless couple.user.id == session[:user_id]
      redirect_to user_couples_path(current_user), alert: "Not authorized"
    end
    # find which user made the team with params[:id]
    # compare that user's id against current_user.id
    # if they do not match up, redirect with a mean message
  end

end

bookNowApp/app/helpers/application_helper.rb
module ApplicationHelper
end

bookNowApp/app/helpers/assistants_helper.rb
module AssistantsHelper
end

bookNowApp/app/helpers/billing_helper.rb
module BillingHelper
end

bookNowApp/app/helpers/couples_helper.rb
module CouplesHelper
end

bookNowApp/app/helpers/errors_helper.rb
module ErrorsHelper
end

bookNowApp/app/helpers/events_helper.rb
module EventsHelper
end

bookNowApp/app/helpers/finances_helper.rb
module FinancesHelper
end

bookNowApp/app/helpers/hooks_helper.rb
module HooksHelper
end

bookNowApp/app/helpers/items_helper.rb
module ItemsHelper
end

bookNowApp/app/helpers/overview_helper.rb
module OverviewHelper
end

bookNowApp/app/helpers/packages_helper.rb
module PackagesHelper
end

bookNowApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

bookNowApp/app/helpers/settings_helper.rb
module SettingsHelper
end

bookNowApp/app/helpers/stripe_helper.rb
module StripeHelper
end

bookNowApp/app/helpers/users_helper.rb
module UsersHelper
end

bookNowApp/app/views/couples/index.html.erb
<% content_for :title, "Wedding Couples" %>

<section class="dashhead">
    <div class="dashhead-titles">
      <h2 class="dashhead-title">Wedding Couples</h2>
    </div>

    <div class="dashhead-toolbar">
    <h4 class="dashhead-status-header status-header status-upcoming">Upcoming: 4</h4>
    <h4 class="dashhead-status-header status-header status-progress">In Progress: 1</h4>
    <h4 class="dashhead-status-header status-header status-complete">Completed: 1</h4>
    </div>
  </section>

  <hr class="m-t-0 m-b">
  <%= link_to "Add New Couple", new_user_couple_path(current_user), class:"p-l btn btn-primary-outline m-b-md" %>

<% unless @couples.blank? %>
  <% @years.each do |year_table| %>
    <% unless year_table.blank? %>
      <div class="table-responsive">
      <h3><%= year_table[0].wedding_date.year %></h3>
          <table class="table" data-sort="table">
            <thead>
              <tr>
                <th class="header">ID</th>
                <th class="header headerSortDown">Wedding Date</th>
                <th class="header">Groom</th>
                <th class="header">Bride</th>
                <th class="header">Location</th>
                <th class="header">Package</th>
                <th class="header">Status</th>
              </tr>
            </thead>
            <tbody>
            
            <% year_table.each do |couple| %>
                <tr class="clickable-row" data-url='<%= couple_path(couple)%>'>
                    <td><a href="#">#<%= couple.id %></a></td>
                    <td><%= couple.wedding_date.strftime('%b %d, %Y') %></td>
                    <td><%= couple.groom_first_name %> <%= couple.groom_last_name %></td>
                    <td><%= couple.bride_first_name %> <%= couple.bride_last_name %></td>
                    <td><%= couple.ceremony_address %></td>
                    <td>{package}</td>
                    <td class="status-upcoming">{status}</td>
                </tr>
            <% end %>

            </tbody>
          </table>
      </div>
    <% end %>
  <% end %>
  <% else %>
    <p>You have no wedding couples yet. Add some!</p>
  <% end %>

bookNowApp/app/views/couples/new.html.erb
<h2>Add New Wedding Couple</h2>

<%= form_for( [@user, @couple], html:{class:"class", role:"form"}) do |f| %>
		
		<div class="row">
			<div class="col-md-3">
				<h4>Wedding Date</h4>

				<fieldset class="form-group">
					<div class="input-append input-group date datepicker" data-date="<%= Time.now.strftime('%m/%d/%Y') %>" data-date-format="mm/dd/yyyy" data-date-viewmode="years">
								<%= f.text_field :wedding_date, class:"span2 form-control", size:"16", value: Time.now.strftime('%m/%d/%Y'), :required => true, :readonly => true %>
								<span class="input-group-addon add-on btn btn-primary"><i class="icon icon-calendar"></i></span>
					</div>
				</fieldset>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-6">

			<h4>Groom</h4>
			
			<fieldset class="form-group">
				<%= f.text_field :groom_first_name, class:"form-control", placeholder:"Groom's First Name", :required => true %>
			</fieldset>
			<fieldset class="form-group">
				<%= f.text_field :groom_last_name, class:"form-control", placeholder:"Groom's Last Name", :required => true %>
			</fieldset>
			<fieldset class="form-group">
				<%= f.text_field :groom_phone, class:"form-control", placeholder:"Groom's Phone" %>
			</fieldset>
			<fieldset class="form-group">
				<%= f.text_field :groom_email, class:"form-control", placeholder:"Groom's Email" %>
			</fieldset>


			<h4>Wedding Coordinator</h4>


			<fieldset class="form-group">
				<%= f.text_field :planner_first_name, class:"form-control", placeholder:"Planner's First Name" %>
			</fieldset>
			<fieldset class="form-group">
				<%= f.text_field :planner_last_name, class:"form-control", placeholder:"Planner's Last Name" %>
			</fieldset>
			<fieldset class="form-group">
				<%= f.text_field :planner_phone, class:"form-control", placeholder:"Planner's Phone" %>
			</fieldset>
			<fieldset class="form-group">
				<%= f.text_field :planner_email, class:"form-control", placeholder:"Planner's Email" %>
			</fieldset>
		</div>
		<div class="col-md-6">
				<h4>Bride</h4>

				<fieldset class="form-group">
					<%= f.text_field :bride_first_name, class:"form-control", placeholder:"Bride's First Name", :required => true %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :bride_last_name, class:"form-control", placeholder:"Bride's Last Name", :required => true %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :bride_phone, class:"form-control", placeholder:"Bride's Phone" %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :bride_email, class:"form-control", placeholder:"Bride's Email" %>
				</fieldset>

				<h4>Locations</h4>

				<fieldset class="form-group">
					<%= f.text_field :groom_location_gr, class:"form-control", placeholder:"What Address is the Groom Getting Ready?" %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :bride_location_gr, class:"form-control", placeholder:"What Address is the Bride Getting Ready?" %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :ceremony_address, class:"form-control", placeholder:"Ceremony Address" %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :reception_address, class:"form-control", placeholder:"Reception Address" %>
				</fieldset>
				<fieldset class="form-group">
					<%= f.text_field :marital_address, class:"form-control", placeholder:"Where Should We Ship Your Movie Package?" %>
				</fieldset>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= f.submit "Add Couple", class:"btn btn-primary" %>
			<%= link_to "< Go Back", user_couples_path(current_user), class:"p-l" %>
		</div>
	</div>

<% end %>

bookNowApp/app/views/couples/show.html.erb
<% content_for :title, "Couples - Overview" %>

  <section class="dashhead">
    <div class="dashhead-titles">
      <h2 class="dashhead-title"><%= @couple.groom_first_name %> and <%= @couple.bride_first_name %></h2>
    </div>

    <div class="dashhead-toolbar">
      <div class="dashead-toolbar-item">
      </div>
      <div class="dashead-toolbar-item">
        <h4 class="dashhead-status-header"><span class="icon icon-calendar"></span> <%= @date.strftime("%B %d, %Y") %></h4>
        <h4><span class="icon icon-location-pin"></span><%= @couple.ceremony_address %></h4>
      </div>
    </div>
  </section>

  <ul class="nav nav-bordered m-t m-b-0" role="tablist">
    <li class="active" role="presentation">
      <a href="#overview" role="tab" data-toggle="tab" aria-controls="overview">Overview</a>
    </li>
    <li role="presentation">
      <a href="#finances" role="tab" data-toggle="tab" aria-controls="finances">Finances</a>
    </li>
    <li role="presentation">
      <a href="#project" role="tab" data-toggle="tab" aria-controls="project">Project</a>
    </li>
  </ul>

  <hr class="m-t-0 m-b-md">

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="overview">
      <div class="row">
        <div class="col-md-8 couples-overview-column">
          <div class="row">
            <div class="col-sm-6">
              <h3 class="couples-info-headings">Groom</h3>
              <table class="couples-info-table">
                <tr>
                  <td><span class="icon icon-user"></span></td>
                  <td><%= @couple.groom_first_name %> <%= @couple.groom_last_name  %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-phone"></span></td>
                  <td><%= @couple.groom_phone %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-mail"></span></td>
                  <td><%= @couple.groom_email %></td>
                </tr>
              </table>
            </div>
            <div class="col-sm-6">
              <h3 class="couples-info-headings">Bride</h3>
              <table class="couples-info-table">
                <tr>
                  <td><span class="icon icon-user"></span></td>
                  <td><%= @couple.bride_first_name %> <%= @couple.bride_last_name %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-phone"></span></td>
                  <td><%= @couple.bride_phone %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-mail"></span></td>
                  <td><%= @couple.bride_email %></td>
                </tr>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <h3 class="couples-info-headings">Coordinator</h3>
              <table class="couples-info-table">
                <tr>
                  <td><span class="icon icon-user"></span></td>
                  <td><%= @couple.planner_first_name %> <%= @couple.planner_last_name %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-phone"></span></td>
                  <td><%= @couple.planner_phone %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-mail"></span></td>
                  <td><%= @couple.planner_email %></td>
                </tr>
              </table>
            </div>
            <div class="col-sm-6">
              <h3 class="couples-info-headings">Photographer</h3>
              <table class="couples-info-table">
                <tr>
                  <td><span class="icon icon-user"></span></td>
                  <td>--</td>
                </tr>
                <tr>
                  <td><span class="icon icon-phone"></span></td>
                  <td>--</td>
                </tr>
                <tr>
                  <td><span class="icon icon-mail"></span></td>
                  <td>--</td>
                </tr>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <h3 class="couples-info-headings">Locations</h3>
              <table class="couples-info-table">
                <tr>
                  <td><span class="icon icon-location-pin"></span> (GROOM) Getting Ready</td>
                  <td><%= @couple.groom_location_gr %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-location-pin"></span> (BRIDE) Getting Ready</td>
                  <td><%= @couple.bride_location_gr %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-location-pin"></span> Ceremony</td>
                  <td><%= @couple.ceremony_address %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-location-pin"></span> Reception</td>
                  <td><%= @couple.reception_address %></td>
                </tr>
                <tr>
                  <td><span class="icon icon-location-pin"></span> Marital Address</td>
                  <td><%= @couple.marital_address %></td>
                </tr>
              </table>
              <div class="well well-lg">
                <p>
                  <span class="icon icon-mobile"></span> Send me a text message reminder 3 DAYS before this wedding event
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">

        <div class="w-md m-x-auto">
          <canvas
            class="ex-graph"
            width="200" height="200"
            data-chart="doughnut"
            data-value="[{ value: 800, color: '#1bc98e', label: 'Initial Deposit' }, { value: 2400, color: '#2d403a', label: 'Remainder Due' }]"
            data-segment-stroke-color="#252830">
          </canvas>
        </div>
        <h5 class="doughnut-headings text-center">Deposit vs Remainder</h5>
        <h4 class="doughnut-data-headings text-center"><span class="payment-deposit-color">800</span> / 3200</h4>
        <div class="w-md m-x-auto">
          <canvas
            class="ex-graph"
            width="200" height="200"
            data-chart="doughnut"
            data-value="[{ value: 45, color: '#1ca8dd', label: 'Percent Completed' }, { value: 55, color: '#2f4750', label: 'Percent Remaining' }]"
            data-segment-stroke-color="#252830">
          </canvas>
        </div>
        <h5 class="doughnut-headings text-center">Project Completion</h5>
        <h4 class="doughnut-data-headings text-center"><span class="project-deposit-color">45</span> / 100</h4>
        </div>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="finances">
      <div class="row">
        <div class="col-md-6">

          <ul class="list-group">
            <li class="list-group-header">Income</li>
            <li class="list-group-item">
              <h4>Fairytale Package - 3200</h4>
              <div class="progress">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100" style="width: 65%"><span class="sr-only">65% Complete</span></div>
              </div>
            
              <table class="table table-income">
                <thead>
                  <tr class="tablehead-subtitle">
                    <th>Date</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>11.05.16</td>
                    <td>John Doe</td>
                    <td>Deposit</td>
                    <td>+ 800.00</td>
                  </tr>
                  <tr>
                    <td>11.05.16</td>
                    <td>John Doe</td>
                    <td>Payment Received</td>
                    <td>+ 1,200.00</td>
                  </tr>
                  <tr>
                    <td colspan="2" class="p-t"><a class="btn btn-sm btn-primary-outline"><span class="icon icon-mail"></span> Request a Payment</a></td>
                    <td class="tablehead-subtitle p-t">Total Income</td>
                    <td class="p-t"><strong>2,000.00</strong></td>
                  </tr>
                </tbody>
              </table>
            </li>
          </ul>
        </div>
        <div class="col-md-5">
          <ul class="list-group">
            <li class="list-group-header">
              Expenses
            </li>
            <li class="list-group-item">
              <table class="table table-expenses">
                <thead>
                  <tr class="tablehead-subtitle">
                    <th>Date</th>
                    <th>Item</th>
                    <th>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>11.07.16</td>
                    <td><span class="icon icon-gauge"></span> Gas Mileage</td>
                    <td class="text-grey">345</td>
                  </tr>
                  <tr>
                    <td>11.07.16</td>
                    <td><span class="icon icon-man"></span> Assistants</td>
                    <td>- 300.00</td>
                  </tr>
                  <tr>
                    <td>11.07.16</td>
                    <td><span class="icon icon-home"></span> Hotel</td>
                    <td>- 240.00</td>
                  </tr>
                  <tr>
                    <td>11.07.16</td>
                    <td><span class="icon icon-aircraft"></span> Airfare</td>
                    <td class="text-muted">- 0.00</td>
                  </tr>
                  <tr>
                    <td>11.07.16</td>
                    <td><span class="icon icon-bowl"></span> Dining</td>
                    <td>- 50.00</td>
                  </tr>
                  <tr>
                  <td>11.07.16</td>
                    <td><span class="icon icon-box"></span> Package Materials</td>
                    <td>- 45.00</td>
                  </tr>
                  <tr>
                  <td>11.07.16</td>
                    <td><span class="icon icon-paper-plane"></span> Shipping</td>
                    <td>- 8.00</td>
                  </tr>
                </tbody>
                <tfoot>
                  <tr>
                    <td class="p-t"><a class="btn btn-sm btn-primary-outline"><span class="icon icon-man"></span> Pay Assistants</a></td>
                    <td class="tablehead-subtitle p-t">Total Expenses</td>
                    <td class="p-t"><strong>643.00</strong></td>
                  </tr>
                </tfoot>
              </table>
            </li>
          </ul>
        </div>
      <!--   <div class="col-md-2">
          <div class="well well-sm">
            <h4><span class="icon icon-mail"></span> Request Payment</h4>
            <p>
              <select class="custom-select custom-select-sm">
                <option>1 Month</option>
                <option>2 Months</option>
                <option>1 Week</option>
                <option>2 Weeks</option>
              </select>

              before the wedding date, send an email to the 
              
              <select class="custom-select custom-select-sm">
                <option>Couple</option>
                <option>Groom</option>
                <option>Bride</option>
              </select>

              gently reminding them that their remaining balance in the amount of

              {AMOUNT}

              is DUE on or before the wedding date.
            
            </p>
            <div class="radio custom-control custom-radio">
              <label>
                <input type="radio" id="radio1" name="radio">
                <span class="custom-control-indicator"></span>
                YES
              </label>
            </div>
            <div class="radio custom-control custom-radio">
              <label>
                <input type="radio" id="radio2" name="radio">
                <span class="custom-control-indicator"></span>
                NO
              </label>
            </div>
            <a href="#"><span class="icon icon-eye"></span> Preview this Email Message</a>
          </div>
          <div class="well well-sm">
            <h4><span class="icon icon-man"></span> Pay Your Assistants</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi illum quae, nulla voluptate? Quo dolore sunt laboriosam molestias doloremque dignissimos, eius corporis, soluta ut saepe reiciendis praesentium laborum unde quasi.</p>
          </div>
        </div> -->
      </div>

    </div>
    <div role="tabpanel" class="tab-pane fade" id="project">
      <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"><span class="sr-only">60% Complete</span></div>
      </div>
      <ul>
        <li>Package Details</li>
        <li>To-Do Lists</li>
        <li>Templates</li>
        <li>Progress Bars</li>
      </ul>
    </div>
  </div>
  </div>
</div>